### ISSUE TITLE
Add helper function `%||%`

### ISSUE THREAD

**Issue by yanyachen** [avantcredit/validationplot#18]
Please add helper function to make the make_validation_plot function runnable

```r
`%||%` <- function(x, y) if (is.null(x)) y else x
```

**Comment by kirillseva** [comment]
Thank you for posting the issue, @yanyachen !
Do you mind reviewing https://github.com/avantcredit/validationplot/pull/19 ? Should fix up your issue

**Comment by yanyachen** [comment]
LGTM, thank you very much
